cc_binary (
  name = "req_rep_test",
  srcs = ["req_rep_test.cpp"],
  deps = [
    "//hermes:hermes"
  ]
)

cc_binary (
  name = "router_dealer_test",
  srcs = ["router_dealer_test.cpp"],
  deps = [
    "//hermes:hermes"
  ],
)
